### ISSUE TITLE
Add more DETER attributes to the AMS analysis units

### ISSUE THREAD

**Issue by lubiavinhas** [terrabrasilis/ams#102]
- Select the attributes that should be included (from the "IBAMA" database)
- Define a layout to display lists of values, such as CAR id's. E.g. display 2 or 3 and a "more" button.

**Comment by andre-carvalho** [comment]
Parent ticket of #97, #98, #99, #100 and #101

**Comment by andre-carvalho** [comment]
All parent tickets are closed
