### ISSUE TITLE
Add DETER-R data sync

### ISSUE THREAD

**Issue by assismauro** [terrabrasilis/ams#112]
To run the updates in AMS database from DETER-B and DETER-R:

**python scripts/update_indicators.py**

To disable the automatic sync via the portal, it's necessary to set the environment variable DETER_DAILY_UPDATE_TIME_INTERVAL equal -1.

**Comment by andre-carvalho** [comment]
This task is included in the "update_indicators.py" script when executing the SQL script with a sequence of instructions to copy  and update data from the DETER-B and DETER-R databases.
