### ISSUE TITLE
Include the Zoom button on the map

### ISSUE THREAD

**Issue by andre-carvalho** [terrabrasilis/ams#210]
Like this.
![Captura de tela de 2024-06-21 11-21-35](https://github.com/terrabrasilis/ams/assets/11821768/2ee8c724-09d4-44c1-8688-efe3889bbdfc)

**Comment by marcoaosilva** [comment]
![zoom](https://github.com/terrabrasilis/ams/assets/69324749/652fca4d-a385-417e-b78d-e049e389c408)
